/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import DailyTasks from '../../components/DailyTasks/DailyTasks';

export default function DailyPage() {
  return <DailyTasks />;
}