/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface ButtonProps {
  children: React.ReactNode;
  className?: string;
  onClick?: () => void;
}

const Button: React.FC<ButtonProps> = ({ children, className, onClick }) => {
  return (
    <button
      onClick={onClick}
      className={`flex overflow-hidden gap-2 justify-center items-center px-3 py-4 max-w-full leading-none whitespace-nowrap bg-amber-500 rounded-lg border border-red-700 border-solid h-[50px] min-h-[50px] w-[230px] ${className}`}
    >
      {children}
    </button>
  );
};

export default Button;