/**
 * This code was generated by Builder.io.
 */
'use client';

import React from 'react';
import FormInput from './FormInput';
import Button from './Button';

const RegistrationForm: React.FC = () => {
  const handleSubmit = (event: React.FormEvent) => {
    event.preventDefault();
    // Handle form submission
  };

  return (
    <form onSubmit={handleSubmit} className="flex absolute left-2/4 z-0 flex-col justify-center items-center p-6 max-w-full rounded-lg border border-solid -translate-x-2/4 bg-stone-900 border-stone-900 bottom-[161px] min-w-[320px] text-[color:var(--sds-color-text-default-tertiary)] translate-y-[0%] w-[672px] max-md:px-5">
      <FormInput label="Должность" placeholder="Введите должность" />
      <FormInput label="Компания" placeholder="Введите компанию" />
      <FormInput label="Номер телефона" placeholder="Введите номер телефона" />
      <FormInput label="Пароль" placeholder="Введите пароль" type="password" />
      <div className="flex gap-4 items-center mt-6 w-full leading-none whitespace-nowrap max-w-[624px] min-h-[40px] text-[color:var(--sds-color-text-brand-on-brand)] max-md:max-w-full">
        <Button className="flex-1 shrink self-stretch p-3 my-auto w-full bg-amber-400 rounded-lg border border-solid basis-0 border-zinc-800 min-w-[240px] max-md:max-w-full">
          Зарегистрироваться
        </Button>
      </div>
    </form>
  );
};

export default RegistrationForm;