/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Button from './Button';
import RegistrationForm from './RegistrationForm';

const RegistrationPage: React.FC = () => {
  return (
    <main className="flex overflow-hidden relative flex-col items-start py-40 text-white bg-stone-900 font-[number:var(--sds-typography-body-font-weight-regular)] text-[length:var(--sds-typography-body-size-medium)]">
      <Button className="absolute right-72 z-0 bottom-[113px]">
        <div className="self-stretch my-auto w-12 opacity-[var(--sds-size-stroke-border)]">
          Войти
        </div>
      </Button>
      <Button className="absolute left-72 z-0 bottom-[113px]">
        <div className="self-stretch my-auto opacity-[var(--sds-size-stroke-border)] w-[155px]">
          создать компанию
        </div>
      </Button>
      <RegistrationForm />
    </main>
  );
};

export default RegistrationPage;