/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import DatabasePage from '../../components/database/DatabasePage';

const DatabasePageWrapper: React.FC = () => {
  return <DatabasePage />;
};

export default DatabasePageWrapper;