/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface CircleImageProps {
  className?: string;
}

const CircleImage: React.FC<CircleImageProps> = ({ className }) => {
  return <div className={`flex shrink-0 max-w-full bg-amber-700 rounded-full ${className}`} />;
};

export default CircleImage;