/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import DocumentDownload from './DocumentDownload';
import CircleImage from './CircleImage';
import TextWithImage from './TextWithImage';

interface DocumentData {
  name: string;
  extension: string;
}

const documents: DocumentData[] = [
  { name: 'Договор', extension: 'docx' },
  { name: 'Таблица', extension: 'xlsx' },
  { name: 'Презентация', extension: 'pptx' },
  { name: 'Список (сгенерировано ИИ)', extension: 'txt' },
];

const DatabasePage: React.FC = () => {
  return (
    <main className="flex overflow-hidden flex-col items-center pt-28 bg-black max-md:pt-24">
      <h1 className="text-6xl leading-none text-center text-white max-md:text-4xl">
        База данных
      </h1>
      {documents.map((doc, index) => (
        <DocumentDownload
          key={index}
          name={doc.name}
          extension={doc.extension}
          className={index === 0 ? 'mt-32' : 'mt-20'}
        />
      ))}
      <section className="self-stretch mt-36 w-full max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-[46%] max-md:ml-0 max-md:w-full">
            <div className="grow mt-20 max-md:mt-10 max-md:max-w-full">
              <div className="flex gap-5 max-md:flex-col">
                <div className="flex flex-col w-[42%] max-md:ml-0 max-md:w-full">
                  <CircleImage className="mt-10 mr-0 h-[475px] w-[622px]" />
                </div>
                <div className="flex flex-col ml-5 w-[58%] max-md:ml-0 max-md:w-full">
                  <div className="flex flex-col items-start pt-16 mx-auto w-full bg-amber-700 rounded-full max-md:max-w-full">
                    <div className="mr-0 max-md:max-w-full">
                      <div className="flex gap-5 max-md:flex-col">
                        <TextWithImage
                          text="Работа с документами"
                          imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/e37bcde78979b7a4c4220de5a0396b21e00243a539c4c233ea8b08732ce59de5?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca"
                          imageAlt="Работа с документами иллюстрация"
                        />
                        <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
                          <CircleImage className="mx-auto h-[452px] w-[791px] max-md:mt-10" />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col ml-5 w-[54%] max-md:ml-0 max-md:w-full">
            <div className="flex gap-10 items-start pt-20 mx-auto w-full bg-amber-700 rounded-full max-md:mt-10 max-md:max-w-full">
              <TextWithImage
                text="Дейлики"
                imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/f215ea1bac723c15775071da987b3a893d08a7451a5d6ae33fcdfa3bb467b14d?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca"
                imageAlt="Дейлики иллюстрация"
                className="mt-36 max-md:mt-10"
              />
              <div className="flex-auto max-md:max-w-full">
                <div className="flex gap-5 max-md:flex-col">
                  <TextWithImage
                    text="База данных"
                    imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/def983f99140353053243f4b14e1f42f714b5ccf18cf4cdb4f81f0e1e04bd79f?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca"
                    imageAlt="База данных иллюстрация"
                    className="z-10 mt-36 mr-0 max-md:mt-10"
                  />
                  <div className="flex flex-col ml-5 w-[44%] max-md:ml-0 max-md:w-full">
                    <CircleImage className="mx-auto h-[514px] w-[308px]" />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
};

export default DatabasePage;