/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface DocumentDownloadProps {
  name: string;
  extension: string;
  className?: string;
}

const DocumentDownload: React.FC<DocumentDownloadProps> = ({ name, extension, className }) => {
  return (
    <div
      className={`overflow-hidden gap-2 self-stretch px-3 py-11 w-full text-6xl leading-none bg-amber-700 rounded-lg border border-solid border-zinc-800 max-w-[1862px] min-h-[149px] text-neutral-100 max-md:mt-10 max-md:max-w-full max-md:text-4xl ${className}`}
    >
      {name}.{extension} Скачать
    </div>
  );
};

export default DocumentDownload;