/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface TextWithImageProps {
  text: string;
  imageSrc: string;
  imageAlt: string;
  className?: string;
}

const TextWithImage: React.FC<TextWithImageProps> = ({ text, imageSrc, imageAlt, className }) => {
  return (
    <div className={`flex flex-col text-6xl leading-none text-center text-white max-md:text-4xl ${className}`}>
      <div className="max-md:max-w-full max-md:text-4xl">{text}</div>
      <img
        loading="lazy"
        src={imageSrc}
        alt={imageAlt}
        className="object-contain self-center mt-10 max-w-full aspect-[1.89] w-[464px]"
      />
    </div>
  );
};

export default TextWithImage;