/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface CircularSectionProps {
  title: string;
  imageSrc: string;
}

const CircularSection: React.FC<CircularSectionProps> = ({ title, imageSrc }) => {
  return (
    <article className="flex flex-col ml-5 w-[54%] max-md:ml-0 max-md:w-full">
      <div className="flex gap-10 items-start pt-20 mx-auto w-full bg-amber-700 rounded-full max-md:mt-10 max-md:max-w-full">
        <div className="flex flex-col mt-36 text-6xl leading-none text-center text-white whitespace-nowrap max-md:mt-10 max-md:text-4xl">
          <h2 className="max-md:text-4xl">{title}</h2>
          <img
            loading="lazy"
            src={imageSrc}
            alt=""
            className="object-contain self-end mt-5 max-w-full aspect-[0.87] w-[236px] max-md:mr-2"
          />
        </div>
        <div className="flex-auto max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            <div className="flex flex-col w-[56%] max-md:ml-0 max-md:w-full">
              <div className="flex z-10 flex-col mt-36 mr-0 text-6xl leading-none text-center text-white max-md:mt-10 max-md:text-4xl">
                <div className="max-md:text-4xl">{title}</div>
                <img
                  loading="lazy"
                  src={imageSrc}
                  alt=""
                  className="object-contain self-center mt-6 max-w-full aspect-[0.95] w-[249px]"
                />
              </div>
            </div>
            <div className="flex flex-col ml-5 w-[44%] max-md:ml-0 max-md:w-full">
              <div className="flex shrink-0 mx-auto max-w-full bg-amber-700 rounded-full h-[514px] w-[308px]" />
            </div>
          </div>
        </div>
      </div>
    </article>
  );
};

export default CircularSection;