/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import DocumentSection from './DocumentSection';
import CircularSection from './CircularSection';

const documentSections = [
  {
    title: "Автоотправка сообщений",
    subtitle: "Алгоритмика",
    description: "Автоматизируйте вашу отправку нужных и частоиспользуемых наборов документов работникам!",
    imageSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/c3b1fd89e1aacc54b9f11d1b9d926b40b157c9c2428a83425b1374a5266411c0?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca"
  },
  {
    title: "Генерация документов",
    subtitle: "Искусственный интеллект",
    description: "Сгенерируйте весь ваш необходимый набор документов!",
    imageSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/c833b722c6245db179deb01e8cbb347b86962610206383d5b465da510071bb81?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca",
    additionalImageSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/965e391ba496cebca275cd674dd6cf68a505a45712b3484ed81b7179eeca9b1b?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca"
  },
  {
    title: "Отправка документов",
    subtitle: "Функции",
    description: "отправьте необходимый набор документов в любом формате с возможностью изменить файл в ручную!",
    imageSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/af337b67efeb4b7d8314aab5bc7e2a30b00fec57e1885a6145d4d9e1a649943c?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca",
    additionalImageSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/984e36bfda462e6f7daa82bd0c10116569047719eb653c4fc93c75e8183a7c34?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca"
  }
];

const circularSections = [
  { title: "Работа с документами", imageSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/c1e1593785db2b02c56bfe27c0d2b646d072a931f06dead72626fb574a0be072?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca" },
  { title: "Дейлики", imageSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/f215ea1bac723c15775071da987b3a893d08a7451a5d6ae33fcdfa3bb467b14d?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca" },
  { title: "База данных", imageSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/5f7cff3867be8058b281a3ae9a20310e535f1b2111b9892725149f6e386f703c?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca" }
];

const DocumentManagementPage: React.FC = () => {
  return (
    <main className="flex overflow-hidden flex-col pt-28 bg-black max-md:pt-24">
      <section className="self-end mr-8 w-full max-w-[2418px] max-md:mr-2.5 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          {documentSections.map((section, index) => (
            <DocumentSection key={index} {...section} />
          ))}
        </div>
      </section>
      <section className="mt-14 w-full max-md:mt-10 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          {circularSections.map((section, index) => (
            <CircularSection key={index} {...section} />
          ))}
        </div>
      </section>
    </main>
  );
};

export default DocumentManagementPage;