/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface DocumentSectionProps {
  title: string;
  subtitle: string;
  description: string;
  imageSrc: string;
  additionalImageSrc?: string;
}

const DocumentSection: React.FC<DocumentSectionProps> = ({
  title,
  subtitle,
  description,
  imageSrc,
  additionalImageSrc
}) => {
  return (
    <article className="flex flex-col w-[28%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow mt-40 text-stone-900 max-md:mt-10 max-md:max-w-full">
        <img
          loading="lazy"
          src={imageSrc}
          alt={title}
          className="object-contain z-10 mr-4 ml-4 w-full rounded-2xl aspect-[1.57] max-md:mr-2.5 max-md:max-w-full"
        />
        <div className="flex flex-col items-start px-4 pt-96 pb-20 mt-0 bg-amber-700 rounded-lg border border-solid border-zinc-300 min-h-[961px] min-w-[240px] max-md:pt-24 max-md:mt-0 max-md:max-w-full">
          <div className="flex flex-col max-w-full w-[541px]">
            <h2 className="w-full text-6xl leading-[90px] max-md:max-w-full max-md:text-4xl max-md:leading-[62px]">
              {title}
            </h2>
            <h3 className="self-start mt-2 text-4xl font-semibold leading-snug whitespace-nowrap">
              {subtitle}
            </h3>
            <p className="flex-1 shrink mt-2 w-full text-4xl text-white leading-[56px] min-h-[281px] max-md:max-w-full">
              {description}
            </p>
          </div>
        </div>
        {additionalImageSrc && (
          <div className="flex overflow-hidden relative z-0 flex-col justify-center items-center w-full h-80 min-h-[320px] opacity-[var(--sds-size-stroke-border)] max-md:max-w-full">
            <img
              loading="lazy"
              src={additionalImageSrc}
              alt=""
              className="object-contain max-w-full aspect-[1.86] w-[624px]"
            />
          </div>
        )}
      </div>
    </article>
  );
};

export default DocumentSection;