/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface InputFieldProps {
  label: string;
  placeholder: string;
  type?: string;
}

const InputField: React.FC<InputFieldProps> = ({ label, placeholder, type = 'text' }) => {
  return (
    <div className="flex flex-col w-full max-md:max-w-full">
      <label className="leading-snug opacity-[var(--sds-size-stroke-border)] max-md:max-w-full">
        {label}
      </label>
      <input
        type={type}
        placeholder={placeholder}
        className="flex overflow-hidden items-center px-4 py-3 mt-2 w-full leading-none bg-white rounded-lg border border-solid border-zinc-300 min-w-[240px] max-md:max-w-full"
        aria-label={label}
      />
    </div>
  );
};

export default InputField;