/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface LoginButtonProps {
  text: string;
}

const LoginButton: React.FC<LoginButtonProps> = ({ text }) => {
  return (
    <button className="flex overflow-hidden flex-1 shrink gap-2 justify-center items-center self-stretch p-3 my-auto w-full bg-amber-400 rounded-lg border border-solid basis-0 border-zinc-800 min-w-[240px] max-md:max-w-full">
      <span className="self-stretch my-auto opacity-[var(--sds-size-stroke-border)]">{text}</span>
    </button>
  );
};

export default LoginButton;