/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import InputField from './InputField';
import LoginButton from './LoginButton';

const LoginForm: React.FC = () => {
  return (
    <main className="flex overflow-hidden flex-col justify-center p-6 rounded-lg border border-solid bg-stone-900 border-stone-900 font-[number:var(--sds-typography-body-font-weight-regular)] text-[color:var(--sds-color-text-default-tertiary)] text-[length:var(--sds-typography-body-size-medium)] max-md:px-5">
      <form className="flex flex-col p-6 w-full rounded-lg border border-solid bg-stone-900 border-stone-900 min-w-[320px] max-md:px-5 max-md:max-w-full">
        <InputField label="Номер телефона" placeholder="Введите номер телефона" type="tel" />
        <div className="mt-6">
          <InputField label="Пароль" placeholder="Введите пароль" type="password" />
        </div>
        <div className="flex gap-4 items-center mt-6 w-full leading-none whitespace-nowrap min-h-[40px] text-[color:var(--sds-color-text-brand-on-brand)] max-md:max-w-full">
          <LoginButton text="Войти" />
        </div>
      </form>
    </main>
  );
};

export default LoginForm;