/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import RegistrationPage from '../../components/registration/RegistrationPage';

export default function RegistrationRoute() {
  return <RegistrationPage />;
}