/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import DocumentManagementPage from '../../components/DocumentManagement/DocumentManagementPage';

export default function Page() {
  return <DocumentManagementPage />;
}