/**
 * This code was generated by Builder.io.
 */
import React, { useState } from 'react';
import InputField from './InputField';
import SubmitButton from './SubmitButton';

interface BusinessRegistrationFormProps {
  onSubmit: (businessName: string) => void;
}

const BusinessRegistrationForm: React.FC<BusinessRegistrationFormProps> = ({ onSubmit }) => {
  const [businessName, setBusinessName] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit(businessName);
  };

  return (
    <form onSubmit={handleSubmit} className="flex overflow-hidden flex-col justify-center p-6 rounded-lg border border-solid bg-stone-900 border-stone-900 font-[number:var(--sds-typography-body-font-weight-regular)] text-[length:var(--sds-typography-body-size-medium)] max-md:px-5">
      <div className="flex flex-col p-6 w-full rounded-lg border border-solid bg-stone-900 border-stone-900 min-w-[320px] max-md:px-5 max-md:max-w-full">
        <InputField
          label="Название бизнеса"
          value={businessName}
          onChange={(e) => setBusinessName(e.target.value)}
          placeholder="Введите название бизнеса"
        />
        <SubmitButton text="Зарегистрировать компанию" />
      </div>
    </form>
  );
};

export default BusinessRegistrationForm;