/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface InputFieldProps {
  label: string;
  value: string;
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  placeholder: string;
}

const InputField: React.FC<InputFieldProps> = ({ label, value, onChange, placeholder }) => {
  return (
    <div className="flex flex-col w-full text-[color:var(--sds-color-text-default-tertiary)] max-md:max-w-full">
      <label htmlFor="businessName" className="leading-snug opacity-[var(--sds-size-stroke-border)] max-md:max-w-full">
        {label}
      </label>
      <input
        id="businessName"
        type="text"
        value={value}
        onChange={onChange}
        placeholder={placeholder}
        className="flex overflow-hidden items-center px-4 py-3 mt-2 w-full leading-none bg-white rounded-lg border border-solid border-zinc-300 min-w-[240px] max-md:max-w-full"
      />
    </div>
  );
};

export default InputField;