/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface SubmitButtonProps {
  text: string;
}

const SubmitButton: React.FC<SubmitButtonProps> = ({ text }) => {
  return (
    <div className="flex gap-4 items-center mt-6 w-full leading-none min-h-[40px] text-[color:var(--sds-color-text-brand-on-brand)] max-md:max-w-full">
      <button
        type="submit"
        className="flex overflow-hidden flex-1 shrink gap-2 justify-center items-center self-stretch p-3 my-auto w-full bg-amber-400 rounded-lg border border-solid basis-0 border-zinc-800 min-w-[240px] max-md:max-w-full"
      >
        <span className="self-stretch my-auto opacity-[var(--sds-size-stroke-border)]">{text}</span>
      </button>
    </div>
  );
};

export default SubmitButton;