/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import TaskCard from './TaskCard';
import WorkWithDocuments from './WorkWithDocuments';

interface Task {
  title: string;
  dueDate: string;
  description: string;
  iconSrc: string;
}

const tasks: Task[] = [
  {
    title: "Заказать лопаты",
    dueDate: "13.08.2024",
    description: "Требуется крупная партия лопат, все подробности в прикрлеплённом документе",
    iconSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/7e577882f88099db823d0a5267bcb41407e755381dd5e9abc62579c088782058?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca"
  },
  {
    title: "Выплатить разнорабочим",
    dueDate: "11.08.2024",
    description: "Разнорабочие уже выполнили всю работу, в файл прикрепляю суммы вылат",
    iconSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/7e577882f88099db823d0a5267bcb41407e755381dd5e9abc62579c088782058?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca"
  },
  {
    title: "Сдать объект заказчику",
    dueDate: "14.08.2024",
    description: "Строительство уже завершено. Сдать его заказчику, подробности в документе",
    iconSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/08de4fdabda683c21923cbdd852f916ddeca5e3812551aafee0198205c61a42f?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca"
  }
];

const DailyTasks: React.FC = () => {
  return (
    <main className="flex overflow-hidden flex-col items-center pt-28 bg-black max-md:pt-24">
      <h1 className="text-6xl leading-none text-center text-white max-md:text-4xl">
        Дейлики
      </h1>
      {tasks.map((task, index) => (
        <TaskCard key={index} {...task} />
      ))}
      <WorkWithDocuments />
    </main>
  );
}

export default DailyTasks;