/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface TaskCardProps {
  title: string;
  dueDate: string;
  description: string;
  iconSrc: string;
}

const TaskCard: React.FC<TaskCardProps> = ({ title, dueDate, description, iconSrc }) => {
  return (
    <section className="flex flex-wrap gap-6 items-start px-6 pt-6 pb-2 mt-14 max-w-full bg-amber-700 rounded-2xl border border-solid border-zinc-300 min-h-[242px] min-w-[240px] w-[1414px] max-md:px-5 max-md:mt-10">
      <img loading="lazy" src={iconSrc} alt="" className="object-contain shrink-0 w-8 aspect-square" />
      <div className="flex flex-col flex-1 shrink basis-0 min-w-[160px] max-md:max-w-full">
        <div className="flex flex-col w-full max-md:max-w-full">
          <h2 className="text-6xl font-semibold tracking-tighter leading-tight text-stone-900 max-md:max-w-full max-md:text-4xl">
            {title} До: {dueDate}
          </h2>
          <p className="mt-2 text-3xl leading-snug text-white max-md:max-w-full">
            {description}
          </p>
        </div>
        <div className="flex relative gap-4 items-start mt-4 w-full text-2xl leading-none text-stone-900 max-md:max-w-full">
          <button className="overflow-hidden gap-2 self-stretch px-3 py-5 my-auto rounded-lg border border-solid bg-neutral-200 border-neutral-500 min-h-[64px] min-w-[240px] w-[277px]">
            Скачать документ
          </button>
          <button className="overflow-hidden absolute gap-2 self-start px-3 py-5 h-16 rounded-lg border border-solid bg-neutral-200 border-neutral-500 min-h-[64px] min-w-[240px] w-[277px]">
            Отправить отчёт
          </button>
        </div>
      </div>
    </section>
  );
}

export default TaskCard;