/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const WorkWithDocuments: React.FC = () => {
  return (
    <section className="self-stretch mt-48 w-full max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-1/5 max-md:ml-0 max-md:w-full">
          <div className="flex shrink-0 mt-28 mr-0 max-w-full bg-amber-700 rounded-full h-[475px] w-[622px] max-md:mt-10" />
        </div>
        <div className="flex flex-col ml-5 w-[27%] max-md:ml-0 max-md:w-full">
          <div className="flex flex-col grow items-start pt-36 pb-7 mt-20 mr-0 text-6xl leading-none text-center text-white bg-amber-700 rounded-full max-md:pt-24 max-md:mt-10 max-md:max-w-full max-md:text-4xl">
            <div className="flex flex-col max-w-full w-[702px] max-md:text-4xl">
              <h2 className="max-md:max-w-full max-md:text-4xl">
                Работа с документами
              </h2>
              <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/e37bcde78979b7a4c4220de5a0396b21e00243a539c4c233ea8b08732ce59de5?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca" alt="Document illustration" className="object-contain self-center mt-10 max-w-full aspect-[1.89] w-[464px]" />
            </div>
          </div>
        </div>
        <div className="flex flex-col ml-5 w-[53%] max-md:ml-0 max-md:w-full">
          <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/29696e4a3853e93be2f60734c8c7067c19a97835dcf393ad9ad5f03afe35d2dc?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca" alt="Work with documents illustration" className="object-contain grow w-full rounded-full aspect-[2.8] max-md:max-w-full" />
        </div>
      </div>
    </section>
  );
}

export default WorkWithDocuments;