/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import RegisterBusinessPage from '../../components/RegisterBusiness/RegisterBusinessPage';

const RegisterBusinessRoute: React.FC = () => {
  return <RegisterBusinessPage />;
};

export default RegisterBusinessRoute;