/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import LoginForm from '../../components/LoginForm/LoginForm';

const LoginPage: React.FC = () => {
  return (
    <div className="flex justify-center items-center min-h-screen bg-gray-100">
      <LoginForm />
    </div>
  );
};

export default LoginPage;