/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const CallToAction: React.FC = () => {
  return (
    <section className="overflow-hidden gap-2 self-stretch px-3 py-9 mt-24 max-w-full text-6xl leading-none bg-amber-700 rounded-3xl border border-solid border-zinc-800 min-h-[138px] text-neutral-100 w-[795px] max-md:mt-10 max-md:max-w-full max-md:text-4xl">
      Попробуй бесплатно!
    </section>
  );
};

export default CallToAction;