/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface ContentSectionProps {
  imageUrl: string;
  text: string;
  isReversed?: boolean;
}

const ContentSection: React.FC<ContentSectionProps> = ({ imageUrl, text, isReversed = false }) => {
  const textContent = (
    <div className={`flex flex-col w-6/12 max-md:ml-0 max-md:w-full ${isReversed ? 'ml-5' : ''}`}>
      <div className={`flex flex-col self-stretch my-auto max-md:mt-10 max-md:max-w-full ${isReversed ? 'text-right' : ''}`}>
        <div className="text-4xl text-white max-md:max-w-full">{text}</div>
      </div>
    </div>
  );

  const imageContent = (
    <div className={`flex flex-col w-6/12 max-md:ml-0 max-md:w-full ${!isReversed ? 'ml-5' : ''}`}>
      <img
        loading="lazy"
        src={imageUrl}
        alt=""
        className="object-contain grow w-full aspect-[1.42] max-md:mt-3 max-md:max-w-full"
      />
    </div>
  );

  return (
    <section className="flex gap-5 max-md:flex-col">
      {isReversed ? (
        <>
          {textContent}
          {imageContent}
        </>
      ) : (
        <>
          {imageContent}
          {textContent}
        </>
      )}
    </section>
  );
};

export default ContentSection;