/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="flex self-stretch mt-24 w-full bg-orange-600 min-h-[8px] max-md:mt-10 max-md:max-w-full" />
  );
};

export default Footer;