/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const Header: React.FC = () => {
  return (
    <header>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/2d0fe1c7e3d0d781aeacc586901107dfaf16741e8e6817371805cd3b03e12b44?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca"
        alt=""
        className="object-contain z-10 self-stretch w-full rounded-none aspect-[1.32] max-md:max-w-full"
      />
    </header>
  );
};

export default Header;