/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Header from './Header';
import Footer from './Footer';

interface LayoutProps {
  children: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div className="flex overflow-hidden flex-col items-center pt-5 pb-20 bg-black border border-black border-solid shadow-[0px_4px_4px_rgba(0,0,0,0.25)]">
      <Header />
      <main className="w-full max-w-[1110px] max-md:max-w-full">{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;