/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Layout from './Layout';
import ContentSection from './ContentSection';
import CallToAction from './CallToAction';

const MyComponent: React.FC = () => {
  const contentSections = [
    {
      imageUrl: "https://cdn.builder.io/api/v1/image/assets/TEMP/9483c32d86f6d91437fbc1bc7682504f925b45a6544b84fb78fbf18c069a153d?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca",
      text: "наш сервис позволяет максимально упростить работу с документами в сфере строительства. Мы - залог успеха ЭДО вашей компании",
      isReversed: true
    },
    {
      imageUrl: "https://cdn.builder.io/api/v1/image/assets/TEMP/57d041934cdb7a002aa3493f09597405a0e8af440966a99f31cb33ee14596a3b?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca",
      text: "система быстрых заданий позволит с высокой производительностью и меньшими затратами времени выдавать задачи. удобная система поможет вам в этом",
      isReversed: false
    },
    {
      imageUrl: "https://cdn.builder.io/api/v1/image/assets/TEMP/e668c802193c16a004718014b4965fcd7e595bf978385591e5c6fb161d00a76e?placeholderIfAbsent=true&apiKey=b48bf0c4f89b45d18df56ebaede862ca",
      text: "удобная база данных позволит получить доступ ко всем документам, которые доступны вашему статусу работника",
      isReversed: true
    }
  ];

  return (
    <Layout>
      <div className="w-full max-w-[1110px] max-md:max-w-full">
        {contentSections.map((section, index) => (
          <React.Fragment key={index}>
            <ContentSection
              imageUrl={section.imageUrl}
              text={section.text}
              isReversed={section.isReversed}
            />
            {index < contentSections.length - 1 && (
              <div className="flex self-stretch mt-24 w-full bg-orange-600 min-h-[8px] max-md:mt-10 max-md:max-w-full" />
            )}
          </React.Fragment>
        ))}
      </div>
      <CallToAction />
    </Layout>
  );
};

export default MyComponent;