/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import FormInput from './FormInput';
import Button from './Button';

const RegistrationForm: React.FC = () => {
  return (
    <main className="flex overflow-hidden relative flex-col items-start py-40 text-white bg-stone-900 font-[number:var(--sds-typography-body-font-weight-regular)] text-[length:var(--sds-typography-body-size-medium)]">
      <Button className="absolute right-72 z-0 bottom-[113px]">
        Войти
      </Button>
      <Button className="absolute left-72 z-0 bottom-[113px]">
        создать компанию
      </Button>
      <form className="flex absolute left-2/4 z-0 flex-col justify-center items-center p-6 max-w-full rounded-lg border border-solid -translate-x-2/4 bg-stone-900 border-stone-900 bottom-[161px] min-w-[320px] text-[color:var(--sds-color-text-default-tertiary)] translate-y-[0%] w-[672px] max-md:px-5">
        <FormInput label="Должность" placeholder="Введите должность" />
        <FormInput label="Компания" placeholder="Введите компанию" />
        <FormInput label="Номер телефона" placeholder="Введите номер телефона" />
        <FormInput label="Пароль" placeholder="Введите пароль" />
        <div className="flex gap-4 items-center mt-6 w-full leading-none whitespace-nowrap max-w-[624px] min-h-[40px] text-[color:var(--sds-color-text-brand-on-brand)] max-md:max-w-full">
          <button className="flex overflow-hidden flex-1 shrink gap-2 justify-center items-center self-stretch p-3 my-auto w-full bg-amber-400 rounded-lg border border-solid basis-0 border-zinc-800 min-w-[240px] max-md:max-w-full">
            <span className="self-stretch my-auto opacity-[var(--sds-size-stroke-border)]">
              Зарегистрироваться
            </span>
          </button>
        </div>
      </form>
    </main>
  );
};

export default RegistrationForm;